services:
  frontend:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/main/js/.next
    environment:
      - NODE_ENV=development

  backend:
    environment:
      - NODE_ENV:development