services:
  frontend:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    working_dir: /app/src/main/js

  backend:
    environment:
      NODE_ENV: development