services:
  frontend:
    platform: linux/amd64
    build:
      target: development
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    volumes:
      - type: bind
        source: ./src/main/frontend/.next
        target: /frontend/.next
      - type: bind
        source: ./src/main/frontend/node_modules
        target: /frontend/node_modules

  backend:
    environment:
      NODE_ENV: development