services:
  frontend:
    build:
      target: production
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_BASE: https://api.retrostore.com

  backend:
    environment:
      NODE_ENV: production

