services:
  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      NEXT_PUBLIC_API_BASE: http://nginx
    develop:
      watch:
        - action: sync
          path: ./src/main/frontend/
          target: /frontend/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  backend:
    environment:
      NODE_ENV: development