services:
  frontend:
    build:
      target: production
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      INTERNAL_API_BASE: http://backend:8080

  backend:
    environment:
      NODE_ENV: production
      JWT_SECRET: uSQMeSGb8NgPcLMuVqJTEm6ZnSeNq9fFtw8Y4Fi7tgU=
