FROM node:20.19.6-alpine3.22 AS base

RUN apk add --no-cache libc6-compat
WORKDIR /app


FROM base AS builder

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
CMD ["next", "build"]

FROM base AS development

ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
CMD ["next", "dev"]


FROM base AS production

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["next", "start"]